Remove unnecessary code and add test cases

diff --git a/bin/dummy-app b/bin/dummy-app
--- a/bin/dummy-app
+++ b/bin/dummy-app
@@ -1,27 +1,17 @@
-#!/usr/bin/env bash
+#!/usr/bin/env ruby
 
-set -e
+root = "#{__dir__}/.."
+app_root = "#{root}/dummy-app"
 
-extension_name="solidus_stripe"
-app_name="dummy-app"
+unless File.exist? "#{app_root}/bin/rails"
+  warn 'Creating the dummy-app app...'
+  Dir.chdir root do
+    system "#{root}/bin/dummy-app" or begin
+      warn 'Automatic creation of the dummy-app app failed'
+      exit 1
+    end
+  end
+end
 
-bin/rails-new "$app_name"
-
-# Stay away from the bundler env of the containing extension.
-function unbundled {
-  echo "~~> Running: $@"
-  ruby -rbundler -e'Bundler.with_unbundled_env {system *ARGV}' -- env BUNDLE_SUPPRESS_INSTALL_USING_MESSAGES=true "$@"
-}
-
-cd ./dummy-app
-
-# Coverage
-echo "require_relative '../../coverage.rb' if ENV['COVERAGE']" >> config/boot.rb
-echo "gem 'rspec_junit_formatter', require: false" >> Gemfile
-echo "gem 'simplecov', '~> 0.22', require: false" >> Gemfile
-echo "gem 'simplecov-cobertura', require: false" >> Gemfile
-echo "gem 'stripe-ruby-mock', group: :test" >> Gemfile
-unbundled bundle install
-
-unbundled bundle add $extension_name --path ..
-unbundled bundle exec rails generate $extension_name:install --migrate --load-seeds=false --specs=all
+Dir.chdir app_root
+exec "#{app_root}/bin/rails", *ARGV
